// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "profile.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace request {
namespace profile {

namespace {

const ::google::protobuf::Descriptor* GetProfileInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetProfileInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_profile_2eproto() {
  protobuf_AddDesc_profile_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "profile.proto");
  GOOGLE_CHECK(file != NULL);
  GetProfileInfo_descriptor_ = file->message_type(0);
  static const int GetProfileInfo_offsets_[1] = {
  };
  GetProfileInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GetProfileInfo_descriptor_,
      GetProfileInfo::default_instance_,
      GetProfileInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetProfileInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetProfileInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GetProfileInfo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_profile_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GetProfileInfo_descriptor_, &GetProfileInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_profile_2eproto() {
  delete GetProfileInfo::default_instance_;
  delete GetProfileInfo_reflection_;
}

void protobuf_AddDesc_profile_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rprofile.proto\022\025proto.request.profile\"\020"
    "\n\016GetProfileInfo", 56);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "profile.proto", &protobuf_RegisterTypes);
  GetProfileInfo::default_instance_ = new GetProfileInfo();
  GetProfileInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_profile_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_profile_2eproto {
  StaticDescriptorInitializer_profile_2eproto() {
    protobuf_AddDesc_profile_2eproto();
  }
} static_descriptor_initializer_profile_2eproto_;


// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

GetProfileInfo::GetProfileInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void GetProfileInfo::InitAsDefaultInstance() {
}

GetProfileInfo::GetProfileInfo(const GetProfileInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void GetProfileInfo::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GetProfileInfo::~GetProfileInfo() {
  SharedDtor();
}

void GetProfileInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GetProfileInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetProfileInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetProfileInfo_descriptor_;
}

const GetProfileInfo& GetProfileInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_profile_2eproto();  return *default_instance_;
}

GetProfileInfo* GetProfileInfo::default_instance_ = NULL;

GetProfileInfo* GetProfileInfo::New() const {
  return new GetProfileInfo;
}

void GetProfileInfo::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GetProfileInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void GetProfileInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* GetProfileInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int GetProfileInfo::ByteSize() const {
  int total_size = 0;
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetProfileInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GetProfileInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GetProfileInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GetProfileInfo::MergeFrom(const GetProfileInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GetProfileInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetProfileInfo::CopyFrom(const GetProfileInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetProfileInfo::IsInitialized() const {
  
  return true;
}

void GetProfileInfo::Swap(GetProfileInfo* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GetProfileInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetProfileInfo_descriptor_;
  metadata.reflection = GetProfileInfo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace profile
}  // namespace request
}  // namespace proto

// @@protoc_insertion_point(global_scope)
