// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_common_2eproto__INCLUDED
#define PROTOBUF_common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_common_2eproto();
void protobuf_AssignDesc_common_2eproto();
void protobuf_ShutdownFile_common_2eproto();

class RequestError;

// ===================================================================

class RequestError : public ::google::protobuf::Message {
 public:
  RequestError();
  virtual ~RequestError();
  
  RequestError(const RequestError& from);
  
  inline RequestError& operator=(const RequestError& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestError& default_instance();
  
  void Swap(RequestError* other);
  
  // implements Message ----------------------------------------------
  
  RequestError* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestError& from);
  void MergeFrom(const RequestError& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 errop = 1;
  inline bool has_errop() const;
  inline void clear_errop();
  static const int kErropFieldNumber = 1;
  inline ::google::protobuf::int32 errop() const;
  inline void set_errop(::google::protobuf::int32 value);
  
  // optional int32 error = 2;
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 2;
  inline ::google::protobuf::int32 error() const;
  inline void set_error(::google::protobuf::int32 value);
  
  // optional string errmsg = 3;
  inline bool has_errmsg() const;
  inline void clear_errmsg();
  static const int kErrmsgFieldNumber = 3;
  inline const ::std::string& errmsg() const;
  inline void set_errmsg(const ::std::string& value);
  inline void set_errmsg(const char* value);
  inline void set_errmsg(const char* value, size_t size);
  inline ::std::string* mutable_errmsg();
  inline ::std::string* release_errmsg();
  
  // @@protoc_insertion_point(class_scope:proto.RequestError)
 private:
  inline void set_has_errop();
  inline void clear_has_errop();
  inline void set_has_error();
  inline void clear_has_error();
  inline void set_has_errmsg();
  inline void clear_has_errmsg();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 errop_;
  ::google::protobuf::int32 error_;
  ::std::string* errmsg_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();
  
  void InitAsDefaultInstance();
  static RequestError* default_instance_;
};
// ===================================================================


// ===================================================================

// RequestError

// optional int32 errop = 1;
inline bool RequestError::has_errop() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestError::set_has_errop() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestError::clear_has_errop() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestError::clear_errop() {
  errop_ = 0;
  clear_has_errop();
}
inline ::google::protobuf::int32 RequestError::errop() const {
  return errop_;
}
inline void RequestError::set_errop(::google::protobuf::int32 value) {
  set_has_errop();
  errop_ = value;
}

// optional int32 error = 2;
inline bool RequestError::has_error() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RequestError::set_has_error() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RequestError::clear_has_error() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RequestError::clear_error() {
  error_ = 0;
  clear_has_error();
}
inline ::google::protobuf::int32 RequestError::error() const {
  return error_;
}
inline void RequestError::set_error(::google::protobuf::int32 value) {
  set_has_error();
  error_ = value;
}

// optional string errmsg = 3;
inline bool RequestError::has_errmsg() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RequestError::set_has_errmsg() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RequestError::clear_has_errmsg() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RequestError::clear_errmsg() {
  if (errmsg_ != &::google::protobuf::internal::kEmptyString) {
    errmsg_->clear();
  }
  clear_has_errmsg();
}
inline const ::std::string& RequestError::errmsg() const {
  return *errmsg_;
}
inline void RequestError::set_errmsg(const ::std::string& value) {
  set_has_errmsg();
  if (errmsg_ == &::google::protobuf::internal::kEmptyString) {
    errmsg_ = new ::std::string;
  }
  errmsg_->assign(value);
}
inline void RequestError::set_errmsg(const char* value) {
  set_has_errmsg();
  if (errmsg_ == &::google::protobuf::internal::kEmptyString) {
    errmsg_ = new ::std::string;
  }
  errmsg_->assign(value);
}
inline void RequestError::set_errmsg(const char* value, size_t size) {
  set_has_errmsg();
  if (errmsg_ == &::google::protobuf::internal::kEmptyString) {
    errmsg_ = new ::std::string;
  }
  errmsg_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RequestError::mutable_errmsg() {
  set_has_errmsg();
  if (errmsg_ == &::google::protobuf::internal::kEmptyString) {
    errmsg_ = new ::std::string;
  }
  return errmsg_;
}
inline ::std::string* RequestError::release_errmsg() {
  clear_has_errmsg();
  if (errmsg_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = errmsg_;
    errmsg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2eproto__INCLUDED
