# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='response.proto',
  package='',
  serialized_pb='\n\x0eresponse.proto\">\n\x0cRequestError\x12\r\n\x05\x65rrop\x18\x01 \x01(\x05\x12\r\n\x05\x65rrno\x18\x02 \x01(\x05\x12\x10\n\x08\x65rrormsg\x18\x03 \x01(\t\"\x1e\n\x0cLoginSuccess\x12\x0e\n\x06userid\x18\x01 \x01(\x03\"\x13\n\x05\x43urHP\x12\n\n\x02hp\x18\x01 \x01(\x02\"\x13\n\x05\x43urMP\x12\n\n\x02mp\x18\x01 \x01(\x02')




_REQUESTERROR = descriptor.Descriptor(
  name='RequestError',
  full_name='RequestError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='errop', full_name='RequestError.errop', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errno', full_name='RequestError.errno', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errormsg', full_name='RequestError.errormsg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=80,
)


_LOGINSUCCESS = descriptor.Descriptor(
  name='LoginSuccess',
  full_name='LoginSuccess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userid', full_name='LoginSuccess.userid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=82,
  serialized_end=112,
)


_CURHP = descriptor.Descriptor(
  name='CurHP',
  full_name='CurHP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hp', full_name='CurHP.hp', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=114,
  serialized_end=133,
)


_CURMP = descriptor.Descriptor(
  name='CurMP',
  full_name='CurMP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='mp', full_name='CurMP.mp', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=135,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['RequestError'] = _REQUESTERROR
DESCRIPTOR.message_types_by_name['LoginSuccess'] = _LOGINSUCCESS
DESCRIPTOR.message_types_by_name['CurHP'] = _CURHP
DESCRIPTOR.message_types_by_name['CurMP'] = _CURMP

class RequestError(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUESTERROR
  
  # @@protoc_insertion_point(class_scope:RequestError)

class LoginSuccess(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGINSUCCESS
  
  # @@protoc_insertion_point(class_scope:LoginSuccess)

class CurHP(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CURHP
  
  # @@protoc_insertion_point(class_scope:CurHP)

class CurMP(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CURMP
  
  # @@protoc_insertion_point(class_scope:CurMP)

# @@protoc_insertion_point(module_scope)
