# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='character.proto',
  package='proto.request.character',
  serialized_pb='\n\x0f\x63haracter.proto\x12\x17proto.request.character\"\x1e\n\x10GetCharacterInfo\x12\n\n\x02id\x18\x01 \x01(\x05')




_GETCHARACTERINFO = descriptor.Descriptor(
  name='GetCharacterInfo',
  full_name='proto.request.character.GetCharacterInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='proto.request.character.GetCharacterInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=44,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['GetCharacterInfo'] = _GETCHARACTERINFO

class GetCharacterInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETCHARACTERINFO
  
  # @@protoc_insertion_point(class_scope:proto.request.character.GetCharacterInfo)

# @@protoc_insertion_point(module_scope)
