# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='profile.proto',
  package='proto.request.profile',
  serialized_pb='\n\rprofile.proto\x12\x15proto.request.profile\"\x10\n\x0eGetProfileInfo')




_GETPROFILEINFO = descriptor.Descriptor(
  name='GetProfileInfo',
  full_name='proto.request.profile.GetProfileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['GetProfileInfo'] = _GETPROFILEINFO

class GetProfileInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETPROFILEINFO
  
  # @@protoc_insertion_point(class_scope:proto.request.profile.GetProfileInfo)

# @@protoc_insertion_point(module_scope)
