// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: character.proto

#ifndef PROTOBUF_character_2eproto__INCLUDED
#define PROTOBUF_character_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace response {
namespace character {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_character_2eproto();
void protobuf_AssignDesc_character_2eproto();
void protobuf_ShutdownFile_character_2eproto();

class GetCharacterInfoResponse;

// ===================================================================

class GetCharacterInfoResponse : public ::google::protobuf::Message {
 public:
  GetCharacterInfoResponse();
  virtual ~GetCharacterInfoResponse();
  
  GetCharacterInfoResponse(const GetCharacterInfoResponse& from);
  
  inline GetCharacterInfoResponse& operator=(const GetCharacterInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetCharacterInfoResponse& default_instance();
  
  void Swap(GetCharacterInfoResponse* other);
  
  // implements Message ----------------------------------------------
  
  GetCharacterInfoResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetCharacterInfoResponse& from);
  void MergeFrom(const GetCharacterInfoResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);
  
  // optional int32 confid = 2;
  inline bool has_confid() const;
  inline void clear_confid();
  static const int kConfidFieldNumber = 2;
  inline ::google::protobuf::int32 confid() const;
  inline void set_confid(::google::protobuf::int32 value);
  
  // optional int32 level = 3;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 3;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);
  
  // optional int32 hp = 4;
  inline bool has_hp() const;
  inline void clear_hp();
  static const int kHpFieldNumber = 4;
  inline ::google::protobuf::int32 hp() const;
  inline void set_hp(::google::protobuf::int32 value);
  
  // optional int32 mp = 5;
  inline bool has_mp() const;
  inline void clear_mp();
  static const int kMpFieldNumber = 5;
  inline ::google::protobuf::int32 mp() const;
  inline void set_mp(::google::protobuf::int32 value);
  
  // optional int32 attack = 6;
  inline bool has_attack() const;
  inline void clear_attack();
  static const int kAttackFieldNumber = 6;
  inline ::google::protobuf::int32 attack() const;
  inline void set_attack(::google::protobuf::int32 value);
  
  // optional int32 defense = 7;
  inline bool has_defense() const;
  inline void clear_defense();
  static const int kDefenseFieldNumber = 7;
  inline ::google::protobuf::int32 defense() const;
  inline void set_defense(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:proto.response.character.GetCharacterInfoResponse)
 private:
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_confid();
  inline void clear_has_confid();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_hp();
  inline void clear_has_hp();
  inline void set_has_mp();
  inline void clear_has_mp();
  inline void set_has_attack();
  inline void clear_has_attack();
  inline void set_has_defense();
  inline void clear_has_defense();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 status_;
  ::google::protobuf::int32 confid_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int32 hp_;
  ::google::protobuf::int32 mp_;
  ::google::protobuf::int32 attack_;
  ::google::protobuf::int32 defense_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];
  
  friend void  protobuf_AddDesc_character_2eproto();
  friend void protobuf_AssignDesc_character_2eproto();
  friend void protobuf_ShutdownFile_character_2eproto();
  
  void InitAsDefaultInstance();
  static GetCharacterInfoResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// GetCharacterInfoResponse

// optional int32 status = 1;
inline bool GetCharacterInfoResponse::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetCharacterInfoResponse::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetCharacterInfoResponse::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetCharacterInfoResponse::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 GetCharacterInfoResponse::status() const {
  return status_;
}
inline void GetCharacterInfoResponse::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
}

// optional int32 confid = 2;
inline bool GetCharacterInfoResponse::has_confid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetCharacterInfoResponse::set_has_confid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetCharacterInfoResponse::clear_has_confid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetCharacterInfoResponse::clear_confid() {
  confid_ = 0;
  clear_has_confid();
}
inline ::google::protobuf::int32 GetCharacterInfoResponse::confid() const {
  return confid_;
}
inline void GetCharacterInfoResponse::set_confid(::google::protobuf::int32 value) {
  set_has_confid();
  confid_ = value;
}

// optional int32 level = 3;
inline bool GetCharacterInfoResponse::has_level() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GetCharacterInfoResponse::set_has_level() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GetCharacterInfoResponse::clear_has_level() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GetCharacterInfoResponse::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 GetCharacterInfoResponse::level() const {
  return level_;
}
inline void GetCharacterInfoResponse::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
}

// optional int32 hp = 4;
inline bool GetCharacterInfoResponse::has_hp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GetCharacterInfoResponse::set_has_hp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GetCharacterInfoResponse::clear_has_hp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GetCharacterInfoResponse::clear_hp() {
  hp_ = 0;
  clear_has_hp();
}
inline ::google::protobuf::int32 GetCharacterInfoResponse::hp() const {
  return hp_;
}
inline void GetCharacterInfoResponse::set_hp(::google::protobuf::int32 value) {
  set_has_hp();
  hp_ = value;
}

// optional int32 mp = 5;
inline bool GetCharacterInfoResponse::has_mp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void GetCharacterInfoResponse::set_has_mp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void GetCharacterInfoResponse::clear_has_mp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void GetCharacterInfoResponse::clear_mp() {
  mp_ = 0;
  clear_has_mp();
}
inline ::google::protobuf::int32 GetCharacterInfoResponse::mp() const {
  return mp_;
}
inline void GetCharacterInfoResponse::set_mp(::google::protobuf::int32 value) {
  set_has_mp();
  mp_ = value;
}

// optional int32 attack = 6;
inline bool GetCharacterInfoResponse::has_attack() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void GetCharacterInfoResponse::set_has_attack() {
  _has_bits_[0] |= 0x00000020u;
}
inline void GetCharacterInfoResponse::clear_has_attack() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void GetCharacterInfoResponse::clear_attack() {
  attack_ = 0;
  clear_has_attack();
}
inline ::google::protobuf::int32 GetCharacterInfoResponse::attack() const {
  return attack_;
}
inline void GetCharacterInfoResponse::set_attack(::google::protobuf::int32 value) {
  set_has_attack();
  attack_ = value;
}

// optional int32 defense = 7;
inline bool GetCharacterInfoResponse::has_defense() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void GetCharacterInfoResponse::set_has_defense() {
  _has_bits_[0] |= 0x00000040u;
}
inline void GetCharacterInfoResponse::clear_has_defense() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void GetCharacterInfoResponse::clear_defense() {
  defense_ = 0;
  clear_has_defense();
}
inline ::google::protobuf::int32 GetCharacterInfoResponse::defense() const {
  return defense_;
}
inline void GetCharacterInfoResponse::set_defense(::google::protobuf::int32 value) {
  set_has_defense();
  defense_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace character
}  // namespace response
}  // namespace proto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_character_2eproto__INCLUDED
