// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

#ifndef PROTOBUF_profile_2eproto__INCLUDED
#define PROTOBUF_profile_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace response {
namespace profile {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_profile_2eproto();
void protobuf_AssignDesc_profile_2eproto();
void protobuf_ShutdownFile_profile_2eproto();

class GetProfileInfoResponse;

// ===================================================================

class GetProfileInfoResponse : public ::google::protobuf::Message {
 public:
  GetProfileInfoResponse();
  virtual ~GetProfileInfoResponse();
  
  GetProfileInfoResponse(const GetProfileInfoResponse& from);
  
  inline GetProfileInfoResponse& operator=(const GetProfileInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetProfileInfoResponse& default_instance();
  
  void Swap(GetProfileInfoResponse* other);
  
  // implements Message ----------------------------------------------
  
  GetProfileInfoResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetProfileInfoResponse& from);
  void MergeFrom(const GetProfileInfoResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);
  
  // optional string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // optional int32 exp = 3;
  inline bool has_exp() const;
  inline void clear_exp();
  static const int kExpFieldNumber = 3;
  inline ::google::protobuf::int32 exp() const;
  inline void set_exp(::google::protobuf::int32 value);
  
  // optional int32 gold = 4;
  inline bool has_gold() const;
  inline void clear_gold();
  static const int kGoldFieldNumber = 4;
  inline ::google::protobuf::int32 gold() const;
  inline void set_gold(::google::protobuf::int32 value);
  
  // optional int32 gem = 5;
  inline bool has_gem() const;
  inline void clear_gem();
  static const int kGemFieldNumber = 5;
  inline ::google::protobuf::int32 gem() const;
  inline void set_gem(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:proto.response.profile.GetProfileInfoResponse)
 private:
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_exp();
  inline void clear_has_exp();
  inline void set_has_gold();
  inline void clear_has_gold();
  inline void set_has_gem();
  inline void clear_has_gem();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::google::protobuf::int32 status_;
  ::google::protobuf::int32 exp_;
  ::google::protobuf::int32 gold_;
  ::google::protobuf::int32 gem_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_profile_2eproto();
  friend void protobuf_AssignDesc_profile_2eproto();
  friend void protobuf_ShutdownFile_profile_2eproto();
  
  void InitAsDefaultInstance();
  static GetProfileInfoResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// GetProfileInfoResponse

// optional int32 status = 1;
inline bool GetProfileInfoResponse::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetProfileInfoResponse::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetProfileInfoResponse::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetProfileInfoResponse::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 GetProfileInfoResponse::status() const {
  return status_;
}
inline void GetProfileInfoResponse::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
}

// optional string name = 2;
inline bool GetProfileInfoResponse::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetProfileInfoResponse::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetProfileInfoResponse::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetProfileInfoResponse::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& GetProfileInfoResponse::name() const {
  return *name_;
}
inline void GetProfileInfoResponse::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void GetProfileInfoResponse::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void GetProfileInfoResponse::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GetProfileInfoResponse::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* GetProfileInfoResponse::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int32 exp = 3;
inline bool GetProfileInfoResponse::has_exp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GetProfileInfoResponse::set_has_exp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GetProfileInfoResponse::clear_has_exp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GetProfileInfoResponse::clear_exp() {
  exp_ = 0;
  clear_has_exp();
}
inline ::google::protobuf::int32 GetProfileInfoResponse::exp() const {
  return exp_;
}
inline void GetProfileInfoResponse::set_exp(::google::protobuf::int32 value) {
  set_has_exp();
  exp_ = value;
}

// optional int32 gold = 4;
inline bool GetProfileInfoResponse::has_gold() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GetProfileInfoResponse::set_has_gold() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GetProfileInfoResponse::clear_has_gold() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GetProfileInfoResponse::clear_gold() {
  gold_ = 0;
  clear_has_gold();
}
inline ::google::protobuf::int32 GetProfileInfoResponse::gold() const {
  return gold_;
}
inline void GetProfileInfoResponse::set_gold(::google::protobuf::int32 value) {
  set_has_gold();
  gold_ = value;
}

// optional int32 gem = 5;
inline bool GetProfileInfoResponse::has_gem() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void GetProfileInfoResponse::set_has_gem() {
  _has_bits_[0] |= 0x00000010u;
}
inline void GetProfileInfoResponse::clear_has_gem() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void GetProfileInfoResponse::clear_gem() {
  gem_ = 0;
  clear_has_gem();
}
inline ::google::protobuf::int32 GetProfileInfoResponse::gem() const {
  return gem_;
}
inline void GetProfileInfoResponse::set_gem(::google::protobuf::int32 value) {
  set_has_gem();
  gem_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace profile
}  // namespace response
}  // namespace proto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_profile_2eproto__INCLUDED
